export { ContentBlockWithImage } from './content-block-with-image'
export { Hero } from './hero'
export { ParallaxPicture } from './parallax-picture'
export { TextWithImages } from './text-with-images'
export { TopDishes } from './top-dishes'
