export { AboutPage } from './about-page'
export { HomePage } from './home-page'
export { PolicyPage } from './policy-page'
export { PromotionsPage } from './promotions-page'
export { TermsPage } from './terms-page'
